name: Semgrep

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: returntocorp/semgrep-action@v1
        with:
          config: >
            p/ci
            p/javascript
          generateSarif: true
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN || '' }}
        continue-on-error: true


